name: qdia_mobile
description: "QDIA Export DZ — marketplace B2B export algérien"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  google_sign_in: ^6.2.2
  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.2
  file_picker: ^8.1.7
  web_socket_channel: ^3.0.1
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.4.0
  path_provider: ^2.1.4
  open_filex: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icon/app_icon.png
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/l10n/
