import { Router, type IRouter } from "express";
import healthRouter from "./health";
import categoriesRouter from "./categories";
import productsRouter from "./products";
import rfqsRouter from "./rfqs";
import suppliersRouter from "./suppliers";
import dashboardRouter from "./dashboard";
import marketplaceRouter from "./marketplace";
import aiRouter from "./ai";
import authRouter from "./auth";
import portsRouter from "./ports";
import customsRouter from "./customs";
import platformRouter from "./platform";
import paymentsRouter from "./payments";
import notificationsRouter from "./notifications";
import documentsRouter from "./documents";
import subscriptionsRouter from "./subscriptions";
import migrationRouter from "./migration";
import billingRouter from "./billing";
import catalogRouter from "./catalog";
import analyticsRouter from "./analytics";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(portsRouter);
router.use(customsRouter);
router.use(platformRouter);
router.use(paymentsRouter);
router.use(notificationsRouter);
router.use(documentsRouter);
router.use(subscriptionsRouter);
router.use(migrationRouter);
router.use(billingRouter);
router.use(catalogRouter);
router.use(analyticsRouter);
router.use(categoriesRouter);
router.use(productsRouter);
router.use(rfqsRouter);
router.use(suppliersRouter);
router.use(dashboardRouter);
router.use(marketplaceRouter);
router.use(aiRouter);

export default router;
